// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAlbums(arg1) {
  return window['go']['main']['App']['GetAlbums'](arg1);
}

export function GetArtists(arg1) {
  return window['go']['main']['App']['GetArtists'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
