// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetAlbums(arg1:Array<main.Param>):Promise<Array<main.Album>>;

export function GetArtists(arg1:Array<main.Param>):Promise<Array<main.Artist>>;

export function PostAlbums(arg1:main.Album):Promise<boolean>;

export function PostArtists(arg1:main.Artist):Promise<boolean>;

export function PostSongs(arg1:main.Song):Promise<boolean>;
